farmacia/config/routes.rb
Rails.application.routes.draw do
 
  resources :compra_detalles
  resources :compras
  devise_for :users
  resources :users
  resources :sale_details
  resources :sales
  resources :clientes
  resources :productos
  resources :proveedors
  resources :tipo_meds
  resources :seccions
  resources :marcas
  
  get 'home/index'

   root 'home#index'

end

farmacia/app/models/compra_detalle.rb
class CompraDetalle < ActiveRecord::Base
	belongs_to :compras
	belongs_to :productos

	has_paper_trail(
    meta: {
      user_id: :user_id, # model attribute
       }
  )
	
	validates :producto_id, presence: true
	validates :cantidad, presence: true
	validates :precio, presence: true

	accepts_nested_attributes_for :productos


	def subtotal
		self.cantidad ? cantidad * unit_price : 0
	end

	def unit_price
		if persisted?
			precio
		else
			producto ? producto.precio_venta : 0
		end
	end
end

farmacia/app/controllers/compra_detalles_controller.rb
class CompraDetallesController < ApplicationController
  before_action :set_compra_detalle, only: [:show, :edit, :update, :destroy]

# GET /sale_details
  # GET /sale_details.json
  def index
    @compra_detalles = @compra.compra_detalle.build
    @compra_detalles.producto = Producto.first
  end


  # GET /sale_details/new
  def new
    @compra_detalles = CompraDetalle.new
  end

  # GET /sale_details/1/edit
  def edit
    @compra_detalles = CompraDetalle.find(params[:id])
  end

  # POST /sale_details
  # POST /sale_details.json
  def create
    producto_exists = false
    producto_id = params[:compra_detalles][:producto_id].to_i
    @sale.compra_detalles.each do |detail|
      if detail.producto_id == producto_id
        # Ya existe el item en la factura, agregar cantidad
        producto_exists = true
        @compra_detalles = detail
        @saved_compra_detalles = detail.id
        break
      end
    end
    if producto_exists
      @compra_detalles.cantidad += params[:compra_detalles][:cantidad].to_i
      @compra_detalles.precio = params[:compra_detalles][:precio].to_f
      @compra_detalles.save!
    else
      compra_detalle = CompraDetalle.new(compra_detalle_params)
      if @compra.compra_detalles.last.nil?
        compra_detalles.number = 1
      else
        compra_detalles.number = @compra.compra_detalles.last.number + 1
      end
      @compra.compra_detalles << compra_detalles
    end
    @compra.save!
    end
  end


  def update
  end

  # DELETE /sale_details/1
  # DELETE /sale_details/1.json
  def destroy
    @compra_detalles = CompraDetalle.find(params[:id])
    @compra_detalles.destroy

    respond_to do |format|
      format.js { render layout: false }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_compra_detalle
      @compra_detalles = CompraDetalle.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def compra_detalle_params
      params.require(:compra_detalles).permit(:compra_id, :number, :producto_id, :cantidad, :precio)
    end
end

farmacia/app/helpers/compra_detalles_helper.rb
module CompraDetallesHelper
end

farmacia/app/views/compra_detalles/_form.html.erb
    <div class="modal-body">
      <%= form_for :compra_detalles, url: compra_compra_detalles_url, method: :post, remote: true do |f| %>
        <div class="row">
          <div class="col-xs-5">
            <div class="form-group">
                <%= f.label :producto_id, class: "sr-only" %>
                <%= f.text_field :producto, placeholder: "Artículo", class: "form-control", value: nil %>
                <%= f.hidden_field :producto_id %>
                <%= hidden_field_tag :prod_descrip  %>
            </div>
          </div>
          <div class="col-xs-2">
            <div class="form-group">
                <%= f.label :cantidad, class: "sr-only" %>
                <%= f.text_field :cantidad, placeholder: "Cant.", class: "form-control" %>
            </div>
          </div>
          <div class="col-xs-2">
            <div class="form-group">
                <%= f.label :precio, class: "sr-only" %>
                <%= f.text_field :precio, placeholder: "Precio", class: "form-control" %>
            </div>
          </div>
          <div class="col-xs-2">
            <div class="form-group">
                <%= f.label :subtotal, class: "sr-only" %>
                <%= f.text_field :subtotal, placeholder: "0", class: "form-control", disabled: true %>
            </div>
          </div>
        </div>
        
          <%= f.submit "Aceptar", class: "btn btn-primary" %>
      <% end %>
    </div>
    <div class="modal-footer">
      <%= link_to "Cancelar", "#", class: "btn btn-danger", "data-dismiss": "modal" %>
    </div>

farmacia/app/views/compra_detalles/_index.html.erb
<% @compra.compra_detalles.each do |detail| %>
  <tr>
    <td><%= detail.number %></td>
    <td><%= detail.producto.prod_descrip %></td>
    <td class="text-right"><%= detail.cantidad %></td>
    <td class="text-right"><%= number_to_currency(detail.precio) %></td>
    <td class="text-right"><%= number_to_currency(detail.subtotal) %></td>
    <% if show_actions %>
      <td><%= link_to "Eliminar", compra_compra_detalles_path(detail.compra.id, detail.id), method: :delete, remote: true %> </td>
    <% end %>
  </tr>
<% end %>

farmacia/app/views/compra_detalles/_new.html.erb
<div class="modal-header">
	<button aria-hidden="true" class="close" data-dismiss="modal" type="button">x</button>
	<h3>Nuevo Detalle</h3>
</div>
<%= render 'form' %>

farmacia/app/views/compra_detalles/_save.js.erb
$("ul.errors").html("");
<% if @compra.compra_detalles.last.errors.any? %>
	<% @compra.compra_detalles.last.errors.full_messages.each do |message| %>
		$("ul.errors").append($("<li />").html(" <%= message.html_safe %> "));
	<% end %>
<% else %>
	$("#compra-detalles").html("<%= escape_javascript(render(partial: 'compra/table', locals: { compra: @compra, show_actions: true })) %>");
	$("#nuevo-detalle-modal").modal("hide");
<% end %>

farmacia/app/views/compra_detalles/create.js.erb
<%= render 'save' %>

farmacia/app/views/compra_detalles/edit.html.erb
<h1>Editing Compra Detalle</h1>

<%= render 'form' %>

<%= link_to 'Show', @compra_detalle %> |
<%= link_to 'Back', compra_detalles_path %>

farmacia/app/views/compra_detalles/new.js.erb
$("#new-detail-modal").html("<%= escape_javascript(render 'new') %>");
$("#new-detail-modal").modal("show");

farmacia/app/views/compra_detalles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Compra:</strong>
  <%= @compra_detalle.compra_id %>
</p>

<p>
  <strong>Number:</strong>
  <%= @compra_detalle.number %>
</p>

<p>
  <strong>Producto:</strong>
  <%= @compra_detalle.producto_id %>
</p>

<p>
  <strong>Cantidad:</strong>
  <%= @compra_detalle.cantidad %>
</p>

<p>
  <strong>Precio:</strong>
  <%= @compra_detalle.precio %>
</p>

<%= link_to 'Edit', edit_compra_detalle_path(@compra_detalle) %> |
<%= link_to 'Back', compra_detalles_path %>