farmacia/config/routes.rb
Rails.application.routes.draw do
 
  resources :compra_detalles
  resources :compras
  devise_for :users
  resources :users
  resources :sale_details
  resources :sales
  resources :clientes
  resources :productos
  resources :proveedors
  resources :tipo_meds
  resources :seccions
  resources :marcas
  
  get 'home/index'

   root 'home#index'

end

farmacia/app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

farmacia/app/models/cliente.rb
class Cliente < ActiveRecord::Base
	has_many :sale
	validates :nombre, :apellido, :ruc, :direccion, :telefono,  presence: true 

	has_paper_trail(
    meta: {
      user_id: :user_id, # model attribute
       }
  )

end

farmacia/app/models/compra.rb
class Compra < ActiveRecord::Base
	has_many :compra_detalles, inverse_of: :compras, dependent: :destroy
	has_many :productos, through: :compra_detalles
	belongs_to :user
	belongs_to :proveedor
	

	has_paper_trail(
	    meta: {
	      user_id: :user_id, # model attribute
	       }
  	)
	
	validates :number, presence: true
	validates :date, presence: true


	accepts_nested_attributes_for :compra_detalles, reject_if: :compra_detalles_rejectable?,
									allow_destroy: true

	enum state: [:draft, :confirmed]

	def total
		details = self.compra_detalles

		total = 0.0
		details.flat_map do |d|
			total += d.cantidad * d.precio
		end
		total
	end

	private

		def sale_detail_rejectable?(att)
			att[:producto_id].blank? || att[:cantidad].blank? || att[:precio].blank? || att[:cantidad].to_f <= 0 || att[:precio].to_f <= 0
		end
end

farmacia/app/models/compra_detalle.rb
class CompraDetalle < ActiveRecord::Base
	belongs_to :compras
	belongs_to :productos

	has_paper_trail(
    meta: {
      user_id: :user_id, # model attribute
       }
  )
	
	validates :producto_id, presence: true
	validates :cantidad, presence: true
	validates :precio, presence: true

	accepts_nested_attributes_for :productos


	def subtotal
		self.cantidad ? cantidad * unit_price : 0
	end

	def unit_price
		if persisted?
			precio
		else
			producto ? producto.precio_venta : 0
		end
	end
end

farmacia/app/models/marca.rb
class Marca < ActiveRecord::Base
	validates :marca_descrip, presence: true
	


	has_many :producto
	
	has_paper_trail(
    meta: {
      user_id: :user_id, # model attribute
       }
  )

end

farmacia/app/models/producto.rb
class Producto < ActiveRecord::Base
 
  belongs_to :marca
  belongs_to :proveedor
  belongs_to :seccion
  belongs_to :tipo_med

  has_paper_trail(
    meta: {
      user_id: :user_id, # model attribute
       }
  )
end

farmacia/app/models/proveedor.rb
class Proveedor < ActiveRecord::Base
	has_many :producto
	validates :ruc, numericality: { only_integer: true } , presence: true
	validates :razon_social,  presence: true
	validates :direccion, presence: true
	validates :telefono, presence: true

	has_paper_trail(
	    meta: {
	      user_id: :user_id, # model attribute
	       }
	  )

	
end

farmacia/app/models/sale.rb
class Sale < ActiveRecord::Base
	has_many :sale_details, inverse_of: :sale, dependent: :destroy
	has_many :productos, through: :sale_details
	belongs_to :user

	has_paper_trail(
	    meta: {
	      user_id: :user_id, # model attribute
	       }
  	)
	
	validates :number, presence: true
	validates :date, presence: true


	accepts_nested_attributes_for :sale_details, reject_if: :sale_detail_rejectable?,
									allow_destroy: true

	enum state: [:draft, :confirmed]

	def total
		details = self.sale_details

		total = 0.0
		details.flat_map do |d|
			total += d.cantidad * d.precio
		end
		total
	end

	private

		def sale_detail_rejectable?(att)
			att[:producto_id].blank? || att[:cantidad].blank? || att[:precio].blank? || att[:cantidad].to_f <= 0 || att[:precio].to_f <= 0
		end
end

farmacia/app/models/sale_detail.rb
class SaleDetail < ActiveRecord::Base
	belongs_to :sale
	belongs_to :producto

	has_paper_trail(
    meta: {
      user_id: :user_id, # model attribute
       }
  )
	
	validates :producto_id, presence: true
	validates :cantidad, presence: true
	validates :precio, presence: true

	accepts_nested_attributes_for :producto


	def subtotal
		self.cantidad ? cantidad * unit_price : 0
	end

	def unit_price
		if persisted?
			precio
		else
			producto ? producto.precio_venta : 0
		end
	end
end

farmacia/app/models/search.rb
class Search
	def initialize(page, page_size, keywords, current_user = nil)
		@page = page
		@page_size = page_size
		@offset = page_size * page
		@keywords = keywords
		@current_user = current_user
	end

	def sales
		if @keywords.present?
		    sales = Sale.where(sale_condition).order(number: :desc).offset(@offset).limit(@page_size)
		    @number_of_records = Producto.where(description_condition).count
	    else
		    sales = Sale.where(state: "confirmed").order(number: :desc).offset(@offset).limit(@page_size)
			@number_of_records = Sale.where(state: "confirmed").count
	    end

		return sales, number_of_pages
	end

	private

	def name_condition
		name_condition = "unaccent(lower(name)) LIKE '%#{I18n.transliterate(@keywords.downcase)}%'"
	end

	def description_condition
		description_condition = "unaccent(lower(description)) LIKE '%#{I18n.transliterate(@keywords.downcase)}%'"
	end

	def sale_condition
		number_condition = "number = #{@keywords.to_i} and user_id = #{@current_user.id} and state = 1"
	end

	def number_of_pages
		number_of_pages = (@number_of_records % @page_size) == 0 ? 
	                        @number_of_records / @page_size - 1 : @number_of_records / @page_size
	end
end

farmacia/app/models/seccion.rb
class Seccion < ActiveRecord::Base
	validates :sec_descrip, presence: true
	
	has_many :producto

	has_paper_trail(
    meta: {
      user_id: :user_id, # model attribute
       }
  )
end

farmacia/app/models/tipo_med.rb
class TipoMed < ActiveRecord::Base
	validates :tipo_descrip, presence: true
	
	has_many :producto
	has_paper_trail(
    meta: {
      user_id: :user_id, # model attribute
       }
  )
end

farmacia/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
	has_paper_trail(
	    meta: {
	      user_id: :user_id, # model attribute
	       }
	  )

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

farmacia/app/helpers/clientes_helper.rb
module ClientesHelper
end

farmacia/app/helpers/compras_helper.rb
module ComprasHelper
end

farmacia/app/helpers/home_helper.rb
module HomeHelper
end

farmacia/app/helpers/marcas_helper.rb
module MarcasHelper
end

farmacia/app/helpers/sales_helper.rb
module SalesHelper
end

farmacia/app/helpers/user_helper.rb
module UserHelper
end

farmacia/app/helpers/users_helper.rb
module UsersHelper
end

farmacia/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Farmacia</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
       
 <% if current_user %> 
<div class="page">
      <!-- Main Navbar-->
      <header class="header">
        <nav class="navbar">
          <!-- Search Box-->
          <div class="search-box">
            <button class="dismiss"><i class="icon-close"></i></button>
            <form id="searchForm" action="#" role="search">
              <input type="search" placeholder="What are you looking for..." class="form-control">
            </form>
          </div>
          <div class="container-fluid">
            <div class="navbar-holder d-flex align-items-center justify-content-between">
              <!-- Navbar Header-->
              <div class="navbar-header">
                <!-- Navbar Brand --><a href="index.html" class="navbar-brand d-none d-sm-inline-block">
                  <div class="brand-text d-none d-lg-inline-block"><span>Farmacia </span><strong>Estrellita</strong></div>
                  <div class="brand-text d-none d-sm-inline-block d-lg-none"><strong>FE</strong></div></a>
                <!-- Toggle Button--><a id="toggle-btn" href="#" class="menu-btn active"><span></span><span></span><span></span></a>
              </div>
              <!-- Navbar Menu -->
            <ul class="nav-menu list-unstyled d-flex flex-md-row align-items-md-center">
           <!-- Logout    -->
                <li class="nav-item">
                <span class="d-none d-sm-inline">           
                         

           <li><%= link_to "Salir ", destroy_user_session_path, method: :delete%></li>
   
          <% else %>

          
            <li><%= link_to "",  new_user_session_path %> </li>

           <% end %>
            <% if current_user %> 
           </span></a></li>
              </ul>
            
            </div>
          </div>
        </nav>
      </header>
      <div class="page-content d-flex align-items-stretch"> 
        <!-- Side Navbar -->
        <nav class="side-navbar">
          <!-- Sidebar Header-->
           <% if current_user %> 
          
          <div class="sidebar-header d-flex align-items-center">
           
             <%= image_tag("avatar-1.jpg", :alt => "rss feed") %>
            <div class="title">
              <h1 class="h4"><%= current_user.name %></h1>
              <% if current_user.admin == true %>
              <p>Administrador</p>
              <%else%>
                <p>Usuario</p>
              <% end %>
            </div>
          </div>
          <% end %>
          <!-- Sidebar Navidation Menus--><span class="heading">Menus</span>
          <ul class="list-unstyled">
                   
      <li class='<%= active_for(controller: "home") %>'><%= link_to 'Inicio', root_path %></li>    

      <li class='<%= active_for(controller: "clientes") %>'><%= link_to 'Clientes', clientes_path %></li>
     
      <li class='<%= active_for(controller: "marcas") %>'><%= link_to 'Marcas', marcas_path %></li>
       
      <li class='<%= active_for(controller: "sales") %>'><%= link_to 'Ventas', sales_path %></li>
       
       <li class='<%= active_for(controller: "productos") %>'><%= link_to 'Productos', productos_path %></li>
      
      <li class='<%= active_for(controller: "seccions") %>'><%= link_to 'Secciones', seccions_path %></li>
            
      <li class='<%= active_for(controller: "tipo_meds") %>'><%= link_to 'Tipo de medicamentos', tipo_meds_path %></li>
      
      <li class='<%= active_for(controller: "proveedors_meds") %>'><%= link_to 'Proveedores', proveedors_path %></li>

      <% if current_user.admin == true %>
      <li><%= link_to 'Usuarios', users_path %></li>
      <% end %>
                    <% end %>
                    <li>           <% if current_user %>

           <li><%= link_to "salir", destroy_user_session_path, method: :delete%></li>

          <% else %>

          
            <li><%= link_to "",  new_user_session_path %> </li>

           <% end %></li>
          
        </nav>
         <% if current_user %>
        <div class="content-inner">
          <!-- Page Header-->
          <!--<header class="page-header">
            <div class="container-fluid">
              <h2 class="no-margin-bottom"></h2>
            </div>
          </header>
          -->
 <% end %>
   

<%= yield %>
</body>
</html>