farmacia/config/routes.rb
Rails.application.routes.draw do
 
  resources :compra_detalles
  resources :compras
  devise_for :users
  resources :users
  resources :sale_details
  resources :sales
  resources :clientes
  resources :productos
  resources :proveedors
  resources :tipo_meds
  resources :seccions
  resources :marcas
  
  get 'home/index'

   root 'home#index'

end

farmacia/app/models/tipo_med.rb
class TipoMed < ActiveRecord::Base
	validates :tipo_descrip, presence: true
	
	has_many :producto
	has_paper_trail(
    meta: {
      user_id: :user_id, # model attribute
       }
  )
end

farmacia/app/controllers/tipo_meds_controller.rb
class TipoMedsController < ApplicationController
  before_action :set_tipo_med, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  before_action :set_paper_trail_whodunnit
  # GET /tipo_meds
  # GET /tipo_meds.json
  def index
    if current_user.admin != false
        @tipo_meds = TipoMed.all
        if params[:tipo_descrip].present?
            @tipo_meds = @tipo_meds.where("tipo_descrip ILIKE ?", "%#{params[:tipo_descrip]}%")
        end
    end

    if current_user.admin != true
      @tipo_meds = TipoMed.where("tipo_active != false")
      if params[:tipo_descrip].present?
        @tipo_meds = @tipo_meds.where("tipo_descrip ILIKE ?", "%#{params[:tipo_descrip]}%")
      end

    end
  end

  # GET /tipo_meds/1
  # GET /tipo_meds/1.json
  def show
  end

  # GET /tipo_meds/new
  def new
    @tipo_med = TipoMed.new
  end

  # GET /tipo_meds/1/edit
  def edit
  end

  # POST /tipo_meds
  # POST /tipo_meds.json
  def create
    @tipo_med = TipoMed.new(tipo_med_params)

    respond_to do |format|
      if @tipo_med.save
        format.html { redirect_to @tipo_med, notice: 'Tipo medicamento fue creado con éxito.' }
        format.json { render :show, status: :created, location: @tipo_med }
      else
        format.html { render :new }
        format.json { render json: @tipo_med.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tipo_meds/1
  # PATCH/PUT /tipo_meds/1.json
  def update
    respond_to do |format|
      if @tipo_med.update(tipo_med_params)
        format.html { redirect_to @tipo_med, notice: 'Tipo medicamento fue actualizado con éxito.' }
        format.json { render :show, status: :ok, location: @tipo_med }
      else
        format.html { render :edit }
        format.json { render json: @tipo_med.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tipo_meds/1
  # DELETE /tipo_meds/1.json
  def destroy
    tipo = TipoMed.find(params[:id])
    tipo.update_attribute(:tipo_active, false)
    redirect_to tipo_med_path
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tipo_med
      @tipo_med = TipoMed.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tipo_med_params
      params.require(:tipo_med).permit(:tipo_descrip, :tipo_active)
    end
end

farmacia/app/helpers/tipo_meds_helper.rb
module TipoMedsHelper
end

farmacia/app/views/tipo_meds/_form.html.erb
<section class="charts">
            <div class="container-fluid">
              <div class="row">
                <!-- Line Charts-->
                <div class="col-lg-8">
                  <div class="line-chart-example card">
                   
                    <div class="card-header d-flex align-items-center">
                      <h3 class="h4">Formulario De tipos De Medicamentos</h3>
                    </div>
            <div class="row">
<%= form_for(@tipo_med) do |f| %>
  <% if @tipo_med.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tipo_med.errors.count, "error") %> prohibited this tipo_med from being saved:</h2>

      <ul>
      <% @tipo_med.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class="col-lg-12">
                  <div class="form d-flex align-items-center">
                
                  <div class="  content">
  <div class="field">
    <%= f.label :tipo_descrip %><br>
    <%= f.text_field :tipo_descrip %>
  </div>
  <div class="field">
    <%= f.label :tipo_active %><br>
    <%= f.check_box :tipo_active %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
 </div>
    </div>
  </div>
 </div>
<% end %>
  </div>
</section>

farmacia/app/views/tipo_meds/edit.html.erb
<section class="charts">
            <div class="container-fluid">
<%= render 'form' %>

<%= link_to 'Mostra', @tipo_med %> |
<%= link_to 'Atras', tipo_meds_path %>
</section>

farmacia/app/views/tipo_meds/index.html.erb
<p id="notice"><%= notice %></p>
  <section class="tables">   
            <div class="container-fluid">
              <div class="row">
                <div class="col-lg-12">
                  <div class="card">
                   
                  
                    <div class="card-header d-flex align-items-center">
                      <h3 class="h4">Tipo de medicamento</h3>
                    </div>
                    <div class="card-body">

                      <!-- formulario de busqueda -->
  <%= form_tag tipo_meds_path, method: :get do %>
      <div class="form-group">
          <%= text_field_tag :tipo_descrip, params[:tipo_descrip], class: "form-control", placeholder: "Descripcion" %>
      </div>
      <%= submit_tag "Buscar", name: nil, class: "btn btn-primary btn-md" %>
  <% end %>
                      <!-- fin formulario de busqueda -->

                      <div class="table-responsive">  
                        <table class="table table-striped">
  <thead>
    <tr>
      <th>Tipo descrip</th>
      <th>Tipo active</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tipo_meds.each do |tipo_med| %>
      <tr>
        <td><%= tipo_med.tipo_descrip %></td>
        <td><%= tipo_med.tipo_active %></td>
        <td><%= link_to 'Mostrar', tipo_med %></td>
        <td><%= link_to 'Editar', edit_tipo_med_path(tipo_med) %></td>
        <td><%= link_to 'Eliminar', tipo_med, method: :delete, data: { confirm: 'Estás seguro?' } %></td>
      </tr>
    <% end %>
  </tbody>

</table>
<%= link_to 'Nuevo Tipo med', new_tipo_med_path %>
</div>
                </div>
              </div>
              </div> 
          </div>
 </section>

farmacia/app/views/tipo_meds/new.html.erb
<section class="charts">
            <div class="container-fluid"> 

<%= render 'form' %>

<%= link_to 'Atras', tipo_meds_path %>
</section>

farmacia/app/views/tipo_meds/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Tipo descrip:</strong>
  <%= @tipo_med.tipo_descrip %>
</p>

<p>
  <strong>Tipo active:</strong>
  <%= @tipo_med.tipo_active %>
</p>

<%= link_to 'Editar', edit_tipo_med_path(@tipo_med) %> |
<%= link_to 'Atras', tipo_meds_path %>