farmacia/config/routes.rb
Rails.application.routes.draw do
 
  resources :compra_detalles
  resources :compras
  devise_for :users
  resources :users
  resources :sale_details
  resources :sales
  resources :clientes
  resources :productos
  resources :proveedors
  resources :tipo_meds
  resources :seccions
  resources :marcas
  
  get 'home/index'

   root 'home#index'

end

farmacia/app/models/sale.rb
class Sale < ActiveRecord::Base
	has_many :sale_details, inverse_of: :sale, dependent: :destroy
	has_many :productos, through: :sale_details
	belongs_to :user

	has_paper_trail(
	    meta: {
	      user_id: :user_id, # model attribute
	       }
  	)
	
	validates :number, presence: true
	validates :date, presence: true


	accepts_nested_attributes_for :sale_details, reject_if: :sale_detail_rejectable?,
									allow_destroy: true

	enum state: [:draft, :confirmed]

	def total
		details = self.sale_details

		total = 0.0
		details.flat_map do |d|
			total += d.cantidad * d.precio
		end
		total
	end

	private

		def sale_detail_rejectable?(att)
			att[:producto_id].blank? || att[:cantidad].blank? || att[:precio].blank? || att[:cantidad].to_f <= 0 || att[:precio].to_f <= 0
		end
end

farmacia/app/controllers/sales_controller.rb
class SalesController < ApplicationController
  before_action :set_sale, only: [:show, :edit, :update, :destroy]
  before_action :set_paper_trail_whodunnit
  # GET /sales
  # GET /sales.json
  def index
    @clientes = Cliente.where("cliente_active != false")
    @sales = Sale.all
    unsaved_sales = Sale.where(state: "draft", user: current_user)
    unsaved_sales.each do |sale|
    sale.destroy
    end

  end
  # GET /sales/1
  # GET /sales/1.json
  def show
    @clientes = Cliente.where("cliente_active != false")
  end

  # GET /sales/new
  def new
    @clientes = Cliente.where("cliente_active != false")
    last_sale = Sale.where(state: "confirmed", user: current_user).maximum('number')
    number =  (last_sale != nil) ? last_sale + 1 : 1
    @sale = Sale.create(date: Date::current, number: number, state: "draft", user: current_user)
    @sale.sale_details.build
    params[:sale_id] = @sale.id.to_s
  end

  # GET /sales/1/edit
  def edit
    @clientes = Cliente.where("cliente_active != false")
  end

  # POST /sales
  # POST /sales.json
  def create
    @clientes = Cliente.where("cliente_active != false")
  end

  # PATCH/PUT /sales/1
  # PATCH/PUT /sales/1.json
  def update
    @clientes = Cliente.where("cliente_active != false")
    @sale.confirmed!
    respond_to do |format|
      if @sale.update(sale_params)
        format.html { redirect_to @sale, notice: 'Sale was successfully updated.' }
        format.json { render :show, status: :ok, location: @sale }
      else
        format.html { render :edit }
        format.json { render json: @sale.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sales/1
  # DELETE /sales/1.json
  def destroy
    @sale.destroy
    respond_to do |format|
      format.html { redirect_to sales_url, notice: 'Venta eliminada' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sale
      @sale = Sale.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sale_params
      params.require(:sale).permit(:number, :date, :user_id, :cliente_id, sale_details_attributes: [:id, :sale_id, :producto_id, :number, :cantidad, :precio, :_destroy] )
    end
end

farmacia/app/helpers/sales_helper.rb
module SalesHelper
end

farmacia/app/views/sales/_form.html.erb
<div class="container-fluid" id="sale-form">
  <div class="row">

    <div class="panel-body">
      <%= form_for(@sale) do |f| %>
        <% if @sale.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(@sale.errors.count, "error") %> prohibited this sale from being saved:</h2>

            <ul>
            <% @sale.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
            </ul>
          </div>
        <% end %>

        <div class="row">
          <div class="col-xs-5 col-md-4">
            <div class="form-group">
              <div class="col-xs-6 col-md-4 text-left">
                <%= f.label :number, "Número" %>
              </div>
              <div class="col-xs-6 col-md-4">
                <%= f.text_field :number, placeholder: "Número", class: "form-control" %>
              </div>
            </div>
          </div>

          <div class="col-xs-8 col-xs-offset-2 col-md-6 col-md-offset-6">
            <div class="form-group">
              <div class="col-xs-4 col-md-4 text-right">
                <%= f.label :date, "Fecha" %>
              </div>
              <div class="col-xs-8 col-md-6 text-right">
                <%= f.date_field :date, placeholder: "Fecha", class: "form-control" %>
              </div>
            </div>
          </div>

          <div class="col-xs-6 col-xs-offset-1 col-md-4 col-md-offset-4">
            <div class="form-group">
              <div class="col-xs-4 col-md-4 text-right">
                <%= f.label :cliente_id, "Cliente" %>
              </div>
              <div class="col-xs-8 col-md-6 text-right">
              <%= select_tag"sale[cliente_id]",  options_for_select(@clientes.map{|c|["#{c.nombre}", c.id]}), id: "cliente_id", placeholder: "Clientes" %>                </div>
            </div>
          </div>

          

        </div>
        <hr>
        <br>
        <div class="panel-body" id="sale-details">
          <%= (@sale.sale_details.count > 0) ? render(partial: 'table', locals: { sale: @sale, show_actions: true }) : 'No hay detalles cargados' %>
        </div>
        <div class="row">
          <div class="col-xs-2 col-xs-offset-5 text-center">

            <%= render 'sale_details/form' %>

            <%# link_to "Nuevo detalle", new_sale_detail_path(sale_id: @sale.id), remote: true, class: "btn btn-info" %>
          </div>
        </div>
        <br>
        <% message = (action_name == 'edit') ? "Volver" : "Aceptar" %>
        <%= f.submit message, class: "btn btn-success" %>
      <% end %>
      <div class="modal fade" id="new-detail-modal" title="Modal">
      </div>
    </div>
  </div>
</div>

<script>
                  $(document).ready(function() {
      $('select#cliente_id').select2({
        placeholder: "Elije un cliente",
        allowClear: true
      });
    });
</script>

farmacia/app/views/sales/_pager.html.erb
<nav>
	<ul class="pager">
		<li class="previous <%= page == 0 ? 'disabled' : '' %>">
			<%= link_to_if page > 0 , "&larr; Anterior".html_safe,
						sales_path(keywords: keywords, page: page - 1) %>
		</li>
		<li class="next <%= page == @number_of_pages ? 'disabled' : '' %>">
			<%= link_to_if page < @number_of_pages, "Siguiente &rarr;".html_safe,
						sales_path(keywords: keywords, page: page + 1) %>
		</li>
	</ul>
</nav>

farmacia/app/views/sales/_results_search.html.erb
<table class="table">
  <thead>
    
    <tr>
      <th></th>
      <th>Número</th>
      <th>Fecha</th>
      <th>Total</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @sales.each do |sale| %>
      <tr>
        <td>
          <%= button_to sale_path(sale), {method: :get, class: "btn btn-info"} do %>
            <span class="glyphicon glyphicon-eye-open" aria-hidden="true"> </span> Ver
          <% end %>
        </td>
        <td><%= sale.number %></td>
        <td><%= sale.date.strftime("%d/%m/%Y") %></td>
        <td><%= number_to_currency(sale.total) %></td>
        <td>
          <%= button_to edit_sale_path(sale), {method: :get, class: "btn btn-info"} do %>
            <span class="glyphicon glyphicon-pencil" aria-hidden="true"> </span> Editar
          <% end %>
        </td>
        <td>
          <%= button_to sale, { method: :delete, data: { confirm: '¿Está seguro?' }, class: "btn btn-danger" } do %>
            <span class="glyphicon glyphicon-trash" aria-hidden="true"> </span> Eliminar
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

farmacia/app/views/sales/_sale_detail_fields.html.erb
<%= form_for :sale_details do |f| %>
  <div class="nested-fields row">
    <div class="col-xs-5">
      <div class="form-group">
          <%= f.label :producto_id, class: "sr-only" %>
          <%= f.text_field :producto, autofocus: true, placeholder: "Artículo", class: "form-control" %>
          <%= f.hidden_field :producto_id %>
      </div>
    </div>
    <div class="col-xs-2">
      <div class="form-group">
          <%= f.label :cantidad, class: "sr-only" %>
          <%= f.text_field :cantidad, placeholder: "Cant.", class: "form-control" %>
      </div>
    </div>
    <div class="col-xs-2">
      <div class="form-group">
          <%= f.label :precio, class: "sr-only" %>
          <%= f.text_field :precio, placeholder: "Precio", class: "form-control" %>
      </div>
    </div>
    <div class="col-xs-2">
      <div class="form-group">
          <%= f.label :subtotal, class: "sr-only" %>
          <%= f.text_field :subtotal, placeholder: "0", class: "form-control", disabled: true %>
      </div>
    </div>
  </div>
  <%= f.submit "Aceptar", class: "btn btn-success", "data-dismiss": "modal" %>
<% end %>

farmacia/app/views/sales/edit.html.erb
<h1>Editing Sale</h1>

<%= render 'form' %>

<%= link_to 'Show', @sale %> |
<%= link_to 'Back', sales_path %>

farmacia/app/views/sales/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Ventas</h1>

<div class="panel panel-default">
  <div class="panel-heading">Ventas</div>
  <div class="panel-body">
    <%= render partial: 'layouts/search_form', locals: { search_entity: 'sales', word: "Venta" } %>
    <br>
    <div class="col-md-5 col-md-offset-5 col-sm-5 col-sm-offset-5">
      <p>
        <%= button_to new_sale_path, {method: :get, class: "btn btn-success"} do %>
          <span class="glyphicon glyphicon-plus" aria-hidden="true"> </span> Nueva Venta
        <% end %>
      </p>
    </div>
  </div>
  <%= render partial: 'results_search' %>
</div>

farmacia/app/views/sales/new.html.erb
<div class="container-fluid">
	<div class="row">
		<h1>Nueva Venta</h1>

		<%= render 'form', sale: @sale %>

		<%= link_to 'Volver', sales_path, data: { confirm: "Se perderán los cambios ¿Está seguro?" } %>
	</div>
</div>

farmacia/app/views/sales/show.html.erb
<div class="container">
    <div class="row">
        <div class="col-xs-12">
    		<div class="invoice-title">
    			<h2>Venta</h2>
    			<h3 class="pull-right">Número # <%= @sale.number %></h3>
    		</div>
    		<hr>
    		<div class="row">
    			<div class="col-xs-6">
    			</div>
    			<div class="col-xs-6 text-right">
    				<address>
    					<strong>Fecha:</strong><br>
    					<%= @sale.date.strftime("%d/%m/%Y") %><br><br>
    				</address>
    			</div>
    		</div>
    		<div class="row">
		    	<div class="col-md-12">
		    		<div class="panel panel-default">
		    			<div class="panel-heading">
		    				<h3 class="panel-title"><strong>Detalles de Venta</strong></h3>
		    			</div>
		    			<div class="panel-body">
		    				<%= render partial: 'table', locals: { sale: @sale } %>
		    			</div>
		    		</div>
		    	</div>
		    </div>
    	</div>
    </div>
</div>

<%= link_to 'Volver', sales_path %>